#http端口
http-port: 82

#HTTPS端口
server:
  port: 80

  ssl:
    key-store: classpath:dongbao-alias.keystore
    key-store-type: JKS
    key-alias: dongbao-alias
    key-store-password: 123456
    key-password: 123456
