spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/wml-dongbao-test?useSSL=false&useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: root
  profiles:
    active: dev
  main:
    allow-bean-definition-overriding: true



mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-value: 1
      logic-not-delete-value: 0
  #UmsMemberMapper.xml位置
  mapper-locations:
    - classpath*:/com/wml/dongbao/ums/mapper/xml/*.xml
  #存放实体类的包位置
  type-aliases-package: com.wml.dongbao.ums.entity

#网上查到的Redis配置
  # REDIS (RedisProperties)
  # Redis数据库索引（默认为0）
  redis:
    database: 0
  # Redis服务器地址
    host: 192.168.66.110
  # Redis服务器连接端口
    port: 6379
  # 连接池最大连接数（使用负值表示没有限制）
    redis:
      jedis:
        pool:
          max-active: 8
  # 连接池最大阻塞等待时间（使用负值表示没有限制）
          max-wait: -1
  # 连接池中的最大空闲连接
          max-idle: 8
  # 连接池中的最小空闲连接
          min-idle: 0
  # 连接超时时间（毫秒）
          timeout: 5000
#kaptcha配置
kaptcha:
  height: 50
  width: 200
  content:
    length: 4
    source: abc
    space: 2
  font:
    color: black
    name: Arial
    size: 40
  background-color:
    from: red
    to: white
  border:
    enabled: true
    color: black
    thickness: 1
